name: "cmake msvc 2019"

# Trigger manually
on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: microsoft/setup-msbuild@v1
    - name: Build
      run: |
        cmake .
        msbuild ALL_BUILD.vcxproj
    - name: Test
      run: msbuild RUN_TESTS.vcxproj
